name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Set up Git user info
        run: |
          git config --global user.email "lehodiep.1999@gmail.com"
          git config --global user.name "lehodiep.1999@gmail.com"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      # - name: Run prettier
      #   run: npm run prettier

      # - name: Run danger
      #   run: npm run danger

      - name: Run  renderDtype
        run: npm run renderDtype

      # - name: Run updateTypeLib
      #   run: npm run updateTypeLib

      # - name: Update typeLibraModule
      #   run: |
      #     rm -rf typeLib
      #     git submodule update --init typeLib
      #     git submodule update --remote typeLib
      #     git config --global user.email "lehodiep.1999@gmail.com"
      #     git config --global user.name "lehodiep.1999@gmail.com"

      #     git add typeLib
      #     git commit -m "Update type - $(date '+%Y-%m-%d %H:%M:%S') - Commit: $GITHUB_SHA - Run ID: $GITHUB_RUN_ID"
      #     git push origin main

      - name: Build
        run: npm run build
