name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{ secrets.ACCTIONS_AT }}

      - name: Set up Git user info
        run: |
          git config --global user.email "lehodiep.1999@gmail.com"
          git config --global user.name "lehodiep.1999@gmail.com"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run prettier
        run: npm run prettier

      # - name: Run danger
      #   run: npm run danger

      - name: Run  renderDtype
        run: npm run renderDtype

      - name: Build
        run: npm run build
