name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run prettier
        run: npm run prettier

      - name: Run danger
        run: npm run danger

      - name: Run  protobuf
        run: npm run protobuf

      - name: Update typeLibraModule
        run: |
          git submodule update --remote typeLibra
          git add typeLibra
          git commit -m "Update type - $(date '+%Y-%m-%d %H:%M:%S') - Commit: $GITHUB_SHA - Run ID: $GITHUB_RUN_ID"
          git push origin main

      - name: Build
        run: npm run build
